x-default: &default
  build: .
  depends_on:
    db:
      condition: service_healthy
    redis:
      condition: service_started
  environment:
    RAILS_ENV: development
    DATABASE_URL: postgres://postgres:postgres@db
    DATABASE_REPLICA_URL: postgres://postgres:postgres@db
    REDIS_URL: redis://redis
  restart: always
  stdin_open: true
  tty: true
  volumes:
    - ./:/app

services:
  web:
    <<: *default
    ports:
      - 3000:3000
  jobs:
    <<: *default
    command: bundle exec sidekiq
  db:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready'"]
      interval: 10s
      timeout: 5s
      retries: 3
  redis:
    image: redis:7.0

volumes:
  db-data:
